
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-02-25T16:25:17-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "73a546aade5bbaf30f57a066c80065c2705273a3",
 "version": "0.0.7+2.g73a546a.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
